exa_prode_homepage:
    pattern:  /
    defaults: { _controller: ExaProdeBundle:Default:index }
    methods: [GET, POST]
    
apuestas_anteriores:
    pattern: /apuestas/anteriores
    defaults: { _controller: ExaProdeBundle:Default:apuestasAnteriores }
    methods: [GET]
    
ranking_jugadores:
  pattern: /ranking/{type}
  defaults: { _controller: ExaProdeBundle:Default:ranking }
  methods: [GET]
  
ws_marcar_partido:
  pattern: /ws/marcarpartido
  defaults: { _controller: ExaProdeBundle:Webservice:marcarPartido }
  methods: [GET]
  
ws_calcular_fecha:
  pattern: /ws/calcularfecha
  defaults: { _controller: ExaProdeBundle:Webservice:calcularFecha }
  methods: [GET]
  
    
