<?php

namespace Exa\ProdeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ApuestaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApuestaRepository extends EntityRepository
{
    
    public function getPorcentajePrediccion($partido, $prediccion) {
        return $this->getEntityManager()->getConnection()->fetchColumn('
            SELECT ROUND((COUNT(*) / (SELECT COUNT(*) FROM Apuesta WHERE `partido_id` = :partido AND prediccion IS NOT NULL)),2)
            FROM Apuesta a
            WHERE `partido_id` = :partido AND prediccion = :prediccion
            GROUP BY prediccion', array(
                'partido' => $partido,
                'prediccion' => $prediccion
            ));        
    }
    
}
