<?php

namespace Exa\ProdeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EquipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipoRepository extends EntityRepository
{
    
    public function findyByNameAndLiga($name, $liga) {
        $query = $this->getEntityManager()
                ->createQuery('SELECT e FROM ExaProdeBundle:Equipo e
                    WHERE e.liga = :liga
                    AND e.name like :name')
                ->setParameters(array(
                    "liga" => $liga,
                    "name" => sprintf("%%%s%%", $name)
                ))
                ->setMaxResults(1);
        
        return $query->getOneOrNullResult();
                
    }
    
}
