<?php

namespace Exa\ProdeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LigaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigaRepository extends EntityRepository
{
    
    public function findByCodigo($codigo) {
        $query = $this->getEntityManager()
                ->createQuery('SELECT l FROM ExaProdeBundle:Liga l
                    WHERE l.codigo = :codigo AND l.activa = :activa')
                ->setParameters(array(
                    "codigo" => $codigo,
                    "activa" => true
                ))
                ->setMaxResults(1);
        return $query->getOneOrNullResult();
    }
}
