<?php

namespace Exa\ProdeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Exa\ProdeBundle\Entity\Fecha;

/**
 * PartidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartidoRepository extends EntityRepository
{    
    public function getPartidoByEquipos(Fecha $fecha, $equipo1, $equipo2) {
        $query = $this->getEntityManager()->createQuery('
            SELECT p FROM ExaProdeBundle:Partido p
            JOIN p.equipo1 e1
            JOIN p.equipo2 e2
            JOIN p.fecha f
            WHERE (e1.name LIKE :equipo1 OR e2.name LIKE :equipo1) 
            AND (e1.name LIKE :equipo2 OR e2.name LIKE :equipo2)
            AND p.jugado = :jugado
            AND p.fecha = :fecha
            ORDER BY f.veda ASC')
                ->setParameters(array(
                    'equipo1' => sprintf("%%%s%%",$equipo1),
                    'equipo2' => sprintf("%%%s%%",$equipo2),
                    'jugado' => false,
                    'fecha' => $fecha
                ))
                ->setMaxResults(1);
        return $query->getOneOrNullResult();
    }
    
}
